package cha8;


/**
* cha8/AllHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cha8/Shape.idl
* Terça-feira, 25 de Outubro de 2016 20h04min39s BRST
*/

abstract public class AllHelper
{
  private static String  _id = "IDL:cha8/All:1.0";

  public static void insert (org.omg.CORBA.Any a, cha8.Shape[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static cha8.Shape[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = cha8.ShapeHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (100, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (cha8.AllHelper.id (), "All", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static cha8.Shape[] read (org.omg.CORBA.portable.InputStream istream)
  {
    cha8.Shape value[] = null;
    int _len0 = istream.read_long ();
    if (_len0 > (100))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value = new cha8.Shape[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = cha8.ShapeHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, cha8.Shape[] value)
  {
    if (value.length > (100))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      cha8.ShapeHelper.write (ostream, value[_i0]);
  }

}
