package cha8;


/**
* cha8/GraphicalObjectHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cha8/Shape.idl
* Terça-feira, 25 de Outubro de 2016 20h04min39s BRST
*/

abstract public class GraphicalObjectHelper
{
  private static String  _id = "IDL:cha8/GraphicalObject:1.0";

  public static void insert (org.omg.CORBA.Any a, cha8.GraphicalObject that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static cha8.GraphicalObject extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "type",
            _tcOf_members0,
            null);
          _tcOf_members0 = cha8.RectangleHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "enclosing",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[2] = new org.omg.CORBA.StructMember (
            "isFilled",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (cha8.GraphicalObjectHelper.id (), "GraphicalObject", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static cha8.GraphicalObject read (org.omg.CORBA.portable.InputStream istream)
  {
    cha8.GraphicalObject value = new cha8.GraphicalObject ();
    value.type = istream.read_string ();
    value.enclosing = cha8.RectangleHelper.read (istream);
    value.isFilled = istream.read_boolean ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, cha8.GraphicalObject value)
  {
    ostream.write_string (value.type);
    cha8.RectangleHelper.write (ostream, value.enclosing);
    ostream.write_boolean (value.isFilled);
  }

}
