package cha8;


/**
* cha8/GraphicalObject.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cha8/Shape.idl
* Terça-feira, 25 de Outubro de 2016 20h04min39s BRST
*/

public final class GraphicalObject implements org.omg.CORBA.portable.IDLEntity
{
  public String type = null;
  public cha8.Rectangle enclosing = null;
  public boolean isFilled = false;

  public GraphicalObject ()
  {
  } // ctor

  public GraphicalObject (String _type, cha8.Rectangle _enclosing, boolean _isFilled)
  {
    type = _type;
    enclosing = _enclosing;
    isFilled = _isFilled;
  } // ctor

} // class GraphicalObject
