package cha8;

/**
* cha8/RectangleHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cha8/Shape.idl
* Terça-feira, 25 de Outubro de 2016 20h04min39s BRST
*/

public final class RectangleHolder implements org.omg.CORBA.portable.Streamable
{
  public cha8.Rectangle value = null;

  public RectangleHolder ()
  {
  }

  public RectangleHolder (cha8.Rectangle initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cha8.RectangleHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cha8.RectangleHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cha8.RectangleHelper.type ();
  }

}
