package cha8;


/**
* cha8/ShapeListPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cha8/Shape.idl
* Terça-feira, 25 de Outubro de 2016 20h04min39s BRST
*/

public abstract class ShapeListPOA extends org.omg.PortableServer.Servant
 implements cha8.ShapeListOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("newShape", new java.lang.Integer (0));
    _methods.put ("allShapes", new java.lang.Integer (1));
    _methods.put ("getVersion", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // cha8/ShapeList/newShape
       {
         try {
           cha8.GraphicalObject g = cha8.GraphicalObjectHelper.read (in);
           cha8.Shape $result = null;
           $result = this.newShape (g);
           out = $rh.createReply();
           cha8.ShapeHelper.write (out, $result);
         } catch (cha8.ShapeListPackage.FullException $ex) {
           out = $rh.createExceptionReply ();
           cha8.ShapeListPackage.FullExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // cha8/ShapeList/allShapes
       {
         cha8.Shape $result[] = null;
         $result = this.allShapes ();
         out = $rh.createReply();
         cha8.AllHelper.write (out, $result);
         break;
       }

       case 2:  // cha8/ShapeList/getVersion
       {
         int $result = (int)0;
         $result = this.getVersion ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:cha8/ShapeList:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ShapeList _this() 
  {
    return ShapeListHelper.narrow(
    super._this_object());
  }

  public ShapeList _this(org.omg.CORBA.ORB orb) 
  {
    return ShapeListHelper.narrow(
    super._this_object(orb));
  }


} // class ShapeListPOA
