package cha8;


/**
* cha8/ShapeListOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cha8/Shape.idl
* Terça-feira, 25 de Outubro de 2016 20h04min39s BRST
*/

public interface ShapeListOperations 
{
  cha8.Shape newShape (cha8.GraphicalObject g) throws cha8.ShapeListPackage.FullException;
  cha8.Shape[] allShapes ();
  int getVersion ();
} // interface ShapeListOperations
