package cha8;


/**
* cha8/ShapePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cha8/Shape.idl
* Terça-feira, 25 de Outubro de 2016 20h04min39s BRST
*/

public abstract class ShapePOA extends org.omg.PortableServer.Servant
 implements cha8.ShapeOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getVersion", new java.lang.Integer (0));
    _methods.put ("getAllState", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // cha8/Shape/getVersion
       {
         int $result = (int)0;
         $result = this.getVersion ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // cha8/Shape/getAllState
       {
         cha8.GraphicalObject $result = null;
         $result = this.getAllState ();
         out = $rh.createReply();
         cha8.GraphicalObjectHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:cha8/Shape:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Shape _this() 
  {
    return ShapeHelper.narrow(
    super._this_object());
  }

  public Shape _this(org.omg.CORBA.ORB orb) 
  {
    return ShapeHelper.narrow(
    super._this_object(orb));
  }


} // class ShapePOA
