package cha8;


/**
* cha8/ShapeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cha8/Shape.idl
* Terça-feira, 25 de Outubro de 2016 20h04min39s BRST
*/

public interface ShapeOperations 
{
  int getVersion ();
  cha8.GraphicalObject getAllState ();
} // interface ShapeOperations
