package cha8;

/**
* cha8/ShapeListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cha8/Shape.idl
* Terça-feira, 25 de Outubro de 2016 20h04min39s BRST
*/

public final class ShapeListHolder implements org.omg.CORBA.portable.Streamable
{
  public cha8.ShapeList value = null;

  public ShapeListHolder ()
  {
  }

  public ShapeListHolder (cha8.ShapeList initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cha8.ShapeListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cha8.ShapeListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cha8.ShapeListHelper.type ();
  }

}
