package cha8.ShapeListPackage;


/**
* cha8/ShapeListPackage/FullException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cha8/Shape.idl
* Terça-feira, 25 de Outubro de 2016 20h04min39s BRST
*/

public final class FullException extends org.omg.CORBA.UserException
{

  public FullException ()
  {
    super(FullExceptionHelper.id());
  } // ctor


  public FullException (String $reason)
  {
    super(FullExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class FullException
