package hellocorba;


/**
* hellocorba/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hellocorba/Hello.idl
* Terça-feira, 25 de Outubro de 2016 20h06min16s BRST
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
