package hellocorba;

/**
* hellocorba/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hellocorba/Hello.idl
* Terça-feira, 25 de Outubro de 2016 20h06min16s BRST
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public hellocorba.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (hellocorba.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = hellocorba.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    hellocorba.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hellocorba.HelloHelper.type ();
  }

}
